source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASProgressHud_Example' do
  pod 'ASProgressHud', :path => '../'
end

target 'ASProgressHud_Tests' do
  pod 'ASProgressHud', :path => '../'

  
end
